import { Config, InteractionConfig, resolveConfig, resolveInteractionConfig, type Config as MnemonConfig } from './config.ts';
import { DocumentManager } from './documents.ts';
import { createRuntimeGraph, LiveMnemonRuntime } from './live-runtime.ts';
import { MnemonLifecycle } from './lifecycle.ts';
import { createRunner } from './runner.ts';
import { RuntimeMemoryController } from './runtime-memory.ts';
import { MnemonService } from './service.ts';
import { MnemonSubagentCoordinator } from './subagent.ts';
import { StorageScopeInspector } from './storage-scope.ts';
import { MnemonPackManager } from './pack.ts';
import { VersionUpdateManager } from './version-updates.ts';
import { MemoryBoot, MemoryExtensionHost } from '../packages/extension-sdk/src/index.ts';
export { BALANCED_RECALL_QUALITY_POLICY, EXHAUSTIVE_RECALL_QUALITY_POLICY, RecallQualityPolicyRegistry, STRICT_RECALL_QUALITY_POLICY, recallQualityPolicies, registerRecallQualityPolicy, } from './recall-quality/index.ts';
export type { RecallQualityCandidate, RecallQualityDecision, RecallQualityPolicy, RecallQualityPolicyContext, } from './recall-quality/index.ts';
export declare const name = "dsh-mnemon";
export declare const provide: string[];
export declare const inject: string[];
export { Config, InteractionConfig, resolveConfig, resolveInteractionConfig, DocumentManager, LiveMnemonRuntime, MemoryBoot, MemoryExtensionHost, MnemonLifecycle, MnemonService, MnemonSubagentCoordinator, RuntimeMemoryController, StorageScopeInspector, MnemonPackManager, VersionUpdateManager, createRunner, createRuntimeGraph };
export type { MnemonConfig };
/** Mount native model tools on every DSH surface and UI RPC only when Web connection exists. */
export declare function apply(rawContext: unknown, config?: MnemonConfig): void;
